### PR TITLE
added companies to conductor table display

### LINKED ISSUE #597: Add company/supplier to the "more" in the conductor tables

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Added companies to the conductor "more information" plus dropdown, including handling for multiple and no companies
### Issues
- Fixes #597 
### Screenshots

screen shot 2015-11-12 at 2 35 08 pm
screen shot 2015-11-12 at 2 36 33 pm

### CODE REVIEW

**Comment by bsmithgall** [comment]
screen shot 2015-11-12 at 3 26 08 pm
screen shot 2015-11-12 at 3 26 04 pm
screen shot 2015-11-12 at 3 25 44 pm

**Comment by bsmithgall** [comment]
screen shot 2015-11-12 at 3 39 33 pm
screen shot 2015-11-12 at 3 39 36 pm

**Comment by msknee** [comment]
great, tabs! 

last change -- change the all caps heading to normal body text.

**Comment by bsmithgall** [comment]
screen shot 2015-11-12 at 3 42 15 pm

**Comment by bsmithgall** [comment]
This also fixes a bug with #539 that would cause a 500-level exception to be thrown.

autom8

It also fixes a small display bug with the "all-contracts" conductor index table.

**Pull request merged**
