### PR TITLE
Beacon pending signup views

### LINKED ISSUE #118: Beacon Architecture Overhaul
Vendor/community facing:
- `/`: Splash/landing page
- `/opportunities`: See lists of opportunities and sign up for updates on individual opportunities. There are also needs for good language when there are no current or upcoming opportunities. @shellicious it would be good to get that when you get a chance.
- `/opportunities/:id`: See an individual opportunity. Post questions to that opportunity. See answers to other questions on that opportunity.
- `/signup`: Sign up for categories
- `/manage`: Manage your subscriptions

City/OMB Facing:
- `/admin/opportunities/pending`: See list of pending opportunities (OMB only) and publish them
- `/admin/opportunities/new`: Submit a new opportunity to OMB
- `/admin/opportunities/:id/edit`: Edit an existing opportunity (publish/unpublish if OMB)
- `/admin/signups`: Small dashboard/view for signed up vendors with download functionality

### PR DESCRIPTION
**Pull request by bsmithgall**
**NOTE**: This also has commits from #127 
### What Changed
- Added a pending view
- Added a current signups download
### Issues
- Fixes #118
### Screencap

autom8
### Screenshots

**Pending opportunities**:
screen shot 2015-07-22 at 2 52 53 pm

**Downloaded Vendors**:
screen shot 2015-07-22 at 2 54 10 pm

### CODE REVIEW

**Comment by msknee** [comment]
Small tweaks:
- "Edit this opportunity" should appear as a link under the Publish button, so that actions that can be taken on a post are in the same place

The nav bar is beginning to be confusing. Ideally, a logged out user would see, from left to right:
- Opportunities
- Subscribe 
- Change subscription 
- City staff log-in

Logged-in city staff see:
- Opportunities
- Subscribe 
- Change subscription 
- Manage opportunities, which is a dropdown with the current links, plus what "Admin" links to now

**Comment by bsmithgall** [comment]
Subscribe or signup? We're using signup everywhere else.

**Comment by bsmithgall** [comment]
screen shot 2015-07-22 at 3 17 23 pm

Agree with what you said about link placement in theory, but it looks weird.

**Comment by msknee** [comment]
@bsmithgall try moving it to the left of the button, and making sure the type size of the title is the same as the edit link, so it's like:

Title --- edit ---- button

**Comment by msknee** [comment]
I like "subscribe" better, because it creates a connection between subscribing and managing a subscription

**Comment by bsmithgall** [comment]
Updated with new comments from @shellicious 

screen shot 2015-07-22 at 3 45 30 pm

**Comment by msknee** [comment]
LBTM

**Pull request merged**
