### PR TITLE
add spec number to searches in admin

### LINKED ISSUE #237: Spec numbers don't work in search admin

### LINKED ISSUE #242: Scout Admin not showing contracts
I'm trying to delete a contract that was accidentally put into scout.  When I search staples in admin only one contract appears when there are 4.

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Contract properties are exposed in the relevant admin pages
- You can search by contract properties
### Issues
- Fixes #237 
- Fixes #242 
### Screencap

screen shot 2015-08-18 at 11 33 20 pm

### CODE REVIEW

**Comment by msknee** [comment]
:+1:

**Comment by bsmithgall** [comment]
Now with companies

screen shot 2015-08-19 at 11 13 42 am

**Comment by msknee** [comment]
:+1:

**Comment by hamhands** [comment]
GO MERGEBOT GO.

**Pull request merged**
