### PR TITLE
database migration for contract types, default stage messages

### LINKED ISSUE #270: New model - Contract Types
This should join with the ContractBase model

### LINKED ISSUE #286: Messages should pre-populate in conductor
This should be configurable from the stage as a root-level property of the stage itself.

Maybe we should also nuke stage properties because they are pretty confusing to end users.

### LINKED ISSUE #298: Flow creation broken in admin
Error log:

```
Aug 26 13:50:56 pittsburgh-purchasing heroku/router: at=info method=POST path="/admin/flow/new/?url=%2Fadmin%2Fflow%2F" host=www.buildpgh.com request_id=c2386071-36e0-4707-9bb0-e47a3e565460 fwd="75.145.32.170" dyno=web.1 connect=1ms service=124ms status=500 bytes=11320 
```

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Added a new model for contract types
- Added default messages for stages, which auto-populate the body of the send update field
### Issues
- fixes #270 
- fixes #286 
- fixes #298 
- works a bit on #79 
### Screencap

autom8

### CODE REVIEW

**Comment by msknee** [comment]
What does the yellow strip in the activity stream represent? A contract in limbo (before it becomes a renewal or bid out again?)

**Comment by bsmithgall** [comment]
I switched the flow.

**Comment by bsmithgall** [comment]
That color is the color you get when the flow is switched.

**Comment by msknee** [comment]
I think the actions that occurred within the previous flow should be colored a variant of the color alongside the whole previous flow.

So either:
- yellow-orange line on outside + lighter yellow-orange lines for actions within it
- gray line on outside + lighter gray lines for actions within it

**Comment by bsmithgall** [comment]
Agreed, but I would rather merge this (esp. because it fixes current prod-breaking bug #298) and open a new issue where we totally revamp the activity log color scheme.

**Comment by msknee** [comment]
@bsmithgall sounds good to me!

**Comment by msknee** [comment]
@bsmithgall I'll open a new issue

**Comment by bsmithgall** [comment]
:+1:

**Pull request merged**
