### PR TITLE
[WIP] new logos

### LINKED ISSUE #192: Consistent logos for Scout / Beacon / Conductor
screen shot 2015-08-08 at 10 45 56 am

### PR DESCRIPTION
**Pull request by hamhands**
### What changed
- added beacon logo to nav and home
- hacky update to styles to match font awesome alignment
### What's needed
- [ ] conductor logos
### Issues
- closes #192 
### Screencap

screen shot 2015-11-12 at 1 55 57 pm

### CODE REVIEW

**Comment by bsmithgall** [comment]
@hamhands don't forget to update the scout button as well!

**Comment by msknee** [comment]
Added Beacon logos that are less fat: https://drive.google.com/drive/u/1/folders/0B24dyIgc537SZnk5cTZySnNSZUE @hamhands

**Comment by hamhands** [comment]
How's this @shellicious?
screen shot 2015-11-17 at 3 16 25 pm

**Comment by hamhands** [comment]
Also, we don't actually need conductor logos right?

**Comment by msknee** [comment]
conductor is nice-to-have, but I'm more concerned with finishing docs + EOY report.

looks good! Can you try moving the Beacon logo 2px to the right? it looks juuuuust slightly off center.

**Comment by hamhands** [comment]
Yeah, it does look a bit off, but it's not in terms of whole pixels:
beacon_logo

**Comment by hamhands** [comment]
What about this?
screen shot 2015-11-17 at 3 28 47 pm

**Comment by msknee** [comment]
It looked the most centered when it was left:13px

**Comment by bsmithgall** [comment]
Make sure that that works on all screen sizes.

**Comment by hamhands** [comment]
I did last week @bsmithgall, but I'll post screenshots

**Comment by hamhands** [comment]
Dropdown:
screen shot 2015-11-17 at 3 59 06 pm

Big logos:
screen shot 2015-11-17 at 3 58 59 pm

**Comment by bsmithgall** [comment]
Beacon def looks off-center

**Comment by hamhands** [comment]
@bsmithgall @shellicious ok, IS THIS OK???:
screen shot 2015-11-17 at 4 02 00 pm

**Comment by hamhands** [comment]
Re ^^^ 
screen shot 2015-11-17 at 4 03 02 pm

**Comment by msknee** [comment]
:+1:

**Pull request merged**
