### PR TITLE
Beacon opportunity detail fixes

### PR DESCRIPTION
**Pull request by msknee**
### What Changed
- Changed noreply@pittsburghpurchasing to beaconbot@ in settings.py
- Addressed changes from #138 
- Added friendlier text to "How do I bid?" and opportunity status
- Fixed logic of when Not Open Yet, Open, and Closed are displayed (@bsmithgall check me on this)
### What's Needed
- @bsmithgall will add collapse.js to Subscribe form
- @bsmithgall I think I uploaded docs for this opportunity, but they're not appearing.
### Screenshot

screen shot 2015-07-31 at 6 02 09 pm

### CODE REVIEW

**Comment by bsmithgall** [comment]
Double check they are there. They are appearing for me -- it's possible that you uploaded them and then lost the upload in the database migration.

**Comment by bsmithgall** [comment]
Which do you prefer @shellicious ?

In the same place:
autom8

On the right sidebar:
autom8

**Comment by msknee** [comment]
@bsmithgall I like it where it is now, on the left. Can "Follow this opportunity" be a yellow button?

**Comment by bsmithgall** [comment]
screen shot 2015-08-01 at 3 48 21 pm

**Comment by msknee** [comment]
@bsmithgall nice! Small tweaks:
- no need for the drop down arrow after "follow this opportunity". Once someone clicks on it, what happens is clear.
- I have a slight preference for a light gray border like you have now, with a white background instead of gray for the form.

**Pull request merged**
