### PR TITLE
Scout bugfixes

### LINKED ISSUE #326: Scout contract feedback email has a few problems
- [ ] Still says Wexplorer in subject
- [ ] link to contract is broken (needs to be an external link)
- [ ] Mailto doesn't work

### LINKED ISSUE #328: Add Scout docs?
Might be valuable to have this as a "need help using Scout?" call out link.

### LINKED ISSUE #329: Feedback link on main page + unsuccessful search
Based on Dave Osterman's feedback, seems like we should put feedback email link in more spaces, especially on the unsuccessful search page ("Is this a mistake?") and the home page for high level feedback.

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Fixed the bugs in the feedback email listed in #326
- Added some new copy to the page in the event of an unsuccessful search
### Issues
- Fixes #326 
- Fixes #329 
- Fixes #328
### Screenshots

screen shot 2015-09-03 at 12 50 49 pm
screen shot 2015-09-03 at 12 49 59 pm
screen shot 2015-09-03 at 12 49 49 pm

### CODE REVIEW

**Comment by bsmithgall** [comment]
screen shot 2015-09-03 at 1 16 45 pm

**Comment by msknee** [comment]
:+1:

**Comment by hamhands** [comment]
@bsmithgall LGTM :+1: 

Only issue I had was a weird config key error with celery when I tried to view the branch locally. Any idea why?

**Comment by hamhands** [comment]
P.S. I really like the help text in the empty results page.

**Pull request merged**
