### PR TITLE
[in-progress] Remaining Scout and Beacon emails

### PR DESCRIPTION
**Pull request by msknee**
#### What Changed
- Email templates and .txt files for #210 
#### What's Needed
- .html and .txt files of unchecked tasks from #210 
- Writing notification methods for transactional emails
#### Screenshots

[TBD]

### CODE REVIEW

**Comment by bsmithgall** [comment]
@shellicious Do you think you could close this PR and re-open it into the `nightly-jobs` branch instead?

**Comment by msknee** [comment]
@bsmithgall sure, how do?

**Comment by bsmithgall** [comment]
I'll go ahead and open it :)

**Comment by bsmithgall** [comment]
Because this has fallen out of sync, I'll just add the files and commit them to the `nightly-jobs` branch directly.

**Pull request closed without merging**
