### PR TITLE
Filter by department

### LINKED ISSUE #10: List of vendors + contracts used by a specific department
From Debra's feedback on 5/6: the goal of this feature would quickly show a list of contracts used by her department, I&P. When she's paying a stack of invoices, she prefers to see a list of vendors (like on her paper spreadsheet), instead of looking up vendors one at a time in Wex.

Ideas for implementing:
- [ ] Use departments already associated with contracts (and consequently, vendors) from Bill/Ed's spreadsheet 
- [x] Create lists from contracts your team is following

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Added "filter" view where you can see a list of contracts that users from a certain department are watching.
### Issues
- Fixes #10 
### Notes
- #8 must be merged as a dependency before this one is merged.
- It doesn't make a whole lot of sense to go through and categorize everything as "departmental" at this point because we don't have a sense of what the "old" data is. Once we have a finalized spreadsheet for the old data, we can go ahead and input this information.
  - On a related note, I'm not totally sure it makes sense for a contract to have a primary top-level "department" field, but it could definitely be a property on that contract.
### Screecap

autom8

### CODE REVIEW

**Comment by bsmithgall** [comment]
Open question -- should this filter be included in the side search? My feeling is that it should be.

**Comment by msknee** [comment]
@bsmithgall: I think the filter should be included in the side search. I don't think a double search box on the first page is the right way to get to departmental contracts. Better would be a link in the top navigation, titled "My department's contracts."

**Comment by bsmithgall** [comment]
@shellicious as part of the Wex dropdown? Also, it's not a search box, it's a dropdown list.

**Comment by bsmithgall** [comment]
Some updated screenshots: 
screen shot 2015-05-11 at 9 03 33 pm
screen shot 2015-05-11 at 9 03 38 pm

**Pull request merged**
