### PR TITLE
Beacon opportunity tweak [WIP]

### LINKED ISSUE #119: Changes to beacon add individual opportunity view
#### Overall changes
- [x] More descriptive text boxes
- [x] Clearer titles & text (who is the contact email? what kind of description? what do you mean by title?)
- [x] Document solicitation needs to be either an explicitly PDF or allow word documents. Right now my preference is to favor PDFs over Word documents because they can't be changed as easily once uploaded, but I'm open to hear other opinions (@hamhands @shellicious)
- [x] Allow you to upload multiple files
#### Documents Needed

People find this section confusing (this was not made any better by our not uploading any document types).
- [ ] How are people supposed to know what documents they need to upload?
- [ ] People need to have links to explicit examples when they are looking at these things.
- [x] Title needs to be clearer

### PR DESCRIPTION
**Pull request by bsmithgall**
**NOTE**: This change requires #130 to be merged before it will work properly
### What Changed
- Better language on the beacon opportunity page
### Issues
- Fixes #119 

@shellicious @hamhands can you clone this down and take a look at the language?

### CODE REVIEW

**Comment by msknee** [comment]
LGTM

**Comment by hamhands** [comment]
LGTM2. Feel free to merge if you're done @bsmithgall

**Comment by hamhands** [comment]
P.S. I'm getting a weird `ValueError: list.remove(x): x not in list` error, but that's probably something wrong with my environment.

**Comment by bsmithgall** [comment]
More info please. When does that happen? Can you post a full traceback?

**Comment by hamhands** [comment]
It happens with two views, maybe more. So far /beacon/signup and /beacon/admin/opportunities/new both return the same error.

**Comment by bsmithgall** [comment]
Can you post the full error message? There is also a new database migration, so make sure you are up to date on that front.

**Comment by hamhands** [comment]
```
ValueError
ValueError: list.remove(x): x not in list

Traceback (most recent call last)
File "/Users/patrickhammons/.virtualenvs/purchasing-suite/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/patrickhammons/.virtualenvs/purchasing-suite/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Users/patrickhammons/.virtualenvs/purchasing-suite/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/patrickhammons/.virtualenvs/purchasing-suite/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/Users/patrickhammons/.virtualenvs/purchasing-suite/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/patrickhammons/.virtualenvs/purchasing-suite/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/patrickhammons/.virtualenvs/purchasing-suite/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/patrickhammons/.virtualenvs/purchasing-suite/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 124, in dispatch_request
return view_func(**req.view_args)
File "/Users/patrickhammons/Documents/pittsburgh-purchasing-suite/purchasing/opportunities/front/views.py", line 102, in signup
display_categories.remove('Select All')
ValueError: list.remove(x): x not in list
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

**Comment by hamhands** [comment]
I ran db upgrade after I pulled. Maybe I need to completely nuke the database and upgrade.

**Comment by bsmithgall** [comment]
Try re-importing the NIGP codes.

```
python manage.py import_nigp --replace t
```

**Comment by hamhands** [comment]
That did it! :+1:

**Comment by hamhands** [comment]
Should we add something about this kind of error to the readme?

**Comment by bsmithgall** [comment]
Nah, that just happened because of DB inconsistencies when things turned over. I think it's probably fine.

**Comment by hamhands** [comment]
giphy

**Comment by bsmithgall** [comment]
Fun with documents needed section

screen shot 2015-07-25 at 2 50 04 pm

**Comment by bsmithgall** [comment]
@shellicious I am working on some of the problems from #119. I did some work to clean up the section (see the screenshot), but the one remaining piece of concrete feedback was around something like "how do I know which documents to use" -- thoughts on this?

**Comment by bsmithgall** [comment]
autom8

delete a doc

**Comment by msknee** [comment]
Changes look good!

One important thing:
- City staff (not OMB) who are filling this out would see a "Submit to OMB" button, not a "Publish" button.

**Comment by bsmithgall** [comment]
@shellicious LEFT: Staff view. RIGHT: Admin view
screen shot 2015-07-27 at 12 13 39 pm

**Comment by msknee** [comment]
@bsmithgall hurrah! Is the "make visible" checkbox necessary? Is there a case in which OMB would publish something but keep it not visible to the public? The idea of invisible publishing confuses me, and might confuse OMB.

**Comment by bsmithgall** [comment]
@shellicious my thinking was to leave it because this page functions both as the "create" and the "edit" view -- if you are OMB and you need to edit a typo or something it seems insane to have to go _back_ to the pending/approval view after you make an edit.

**Comment by msknee** [comment]
@bsmithgall possible to have the button say "Publish opportunity" the first time it goes from unapproved --> approved and published, and then "Publish changes" afterwards?

**Comment by msknee** [comment]
I agree that OMB should be able to easy edit and save changes in addition to publishing. But the "make visible" box isn't communicating those two workflows.

**Pull request merged**
