### PR TITLE
Publish opportunities

### LINKED ISSUE #63: Form to add opportunities to Beacon
Features to implement:
- [x] Form on the backend to create new opportunities
- [x] View on frontend for listing and details for opportunities
- [ ] Sign up for notifications on specific contracts

Things we need to think about:
- How do we send notifications? Automatically? If so, what are the triggers? What is the content for the notifications?

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Added opportunity create form, edit form
- Added opportunity browse view
- Added S3 file upload for opportunity documents
### Issues
- Fixes #63 
- Fixes "Beacon" portion of #52 
### TODO
- [x] Implement Detail Page
- [x] Fix up navbar
- [x] Implement direct vendor <--> opportunity connection
- [x] Unit tests
### Screencap
- Screencap will happen when progress is completed on the remaining items

### CODE REVIEW

**Comment by bsmithgall** [comment]
So the open question on this is how to actually do the "sign up to notify me about this" -- the main trouble is that on the original signup page we ask for a bunch of info (email/business name are mandatory). How do we want to re-ask for this? Do we want to just ask for email address & business name and if they aren't in there, we can take them to the main signup page and ask them to fill out the rest? Do we duplicate the whole signup form?

**Comment by bsmithgall** [comment]
A bit more to do:
- [x] If you are signed in, you should be to see everything, even stuff that is currently "unpublished"
- [x] Bulk sign-up for information/alternatively, if you are signed in, you should probably be able to publish things.
- [x] Only 'conductor' role should be able to make a contract visible (both on the list view and on the opp admin view)
- [x] Pick a width

**Comment by bsmithgall** [comment]
Screencap:

autom8

**Comment by msknee** [comment]
Overall, looks great to me!

Try moving the sign-up for updates about a specific opportunity section (2 text boxes and a button) over the right side of the page, above the timeline. Add a heading that says "Follow this opportunity". I see now that this section is somewhat confusing on the left side of the page, in the middle of information about the opportunity.

**Comment by bsmithgall** [comment]
Like this? Note I have to futz with the column sizes to make things fit properly.

screen shot 2015-07-09 at 11 22 51 am

What if we just moved it to the very bottom of that section?

screen shot 2015-07-09 at 11 26 55 am

**Comment by msknee** [comment]
@bsmithgall I like below better. Good idea. 

Some of the text in the "how do I bid?" section is redundant. Let's change the text to: "We'll update this opportunity with specific instructions for bidding soon. Sign up below to get updates as they happen."

**Pull request merged**
