### PR TITLE
Email digest

### LINKED ISSUE #344: Add way to unsubscribe from biweekly digest in Manage Subscriptions
Currently there's no way to do it.

### LINKED ISSUE #383: Save as draft --> publish not triggering emails
When adding opp for #380, saving as draft and then publishing didn't trigger emails. Is this an issue with publishing directly or something else?

### LINKED ISSUE #385: Remove 9/10 event RSVP from Beacon

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Added biweekly digest
- Added ability to manage biweekly digest subscriptions
### Issues
- Fixes #344 
- Fixes #383
- Fixes #385 
### What's needed

@shellicious is going to make some copy changes to make us a bit less excited!

### CODE REVIEW

**Comment by bsmithgall** [comment]
The first one of these will go out tomorrow if we merge now.

**Comment by msknee** [comment]
good point. What about sending out the first one on October 1, when most vendors will have actually been on Scout for 2 weeks?

**Comment by bsmithgall** [comment]
Ok, in that case we can merge this tomorrow?

**Comment by bsmithgall** [comment]
Actually, I think it would be better to unregister the bikweekly task, merge this, and then re-register it tomorrow.

**Comment by bsmithgall** [comment]
TODO: make the biweekly only appear if you are subsribed.

**Comment by msknee** [comment]
Also TODO:
- [ ] On Manage Subscriptions, change the header text to a single header that says "Check the boxes to unsubscribe from the following categories"

screen shot 2015-09-15 at 11 31 23 am

**Pull request merged**
