### PR TITLE
Conductor frontpage

### LINKED ISSUE #78: Better front page for conductor
There are few obvious things that should be done here:
- Move up the assigned contracts to their own demarcated section
- Make the table a bit better (perhaps with [datatables](https://www.datatables.net/))

There are probably other fixes that can be made, but this seems like a good place to start.

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Introduced new frontend dependency for conductor -- datatable
- Hooked datatable into conductor's front page
### Issues
- Fixes #78 
### Screencap

autom8

Color is a bit weird in the screencap -- here's a screenshot as well:
screen shot 2015-07-08 at 10 29 05 pm

### CODE REVIEW

**Comment by msknee** [comment]
Small change: move the sort icon(s) 10-15px to the left of the category name. Currently it looks like the icons are connected to the category to the right, since they're spaced far over to the right.

Otherwise, awesome!

**Comment by bsmithgall** [comment]
They are dynamically attached to the table by the DataTables library, so this is actually a lot harder than it should be. There are two fairly simple options:
1. We could override the CSS and have the sort icons to the left of the labels in question
2. We could add cell borders

**Comment by bsmithgall** [comment]
Here's what it looks like with the left of the labels: http://jsfiddle.net/ttcz5odt/

**Comment by msknee** [comment]
@bsmithgall I like that better!

**Pull request merged**
