### PR TITLE
Overhaul of conductor

### LINKED ISSUE #106: Properly handle completed contracts in conductor
They currently 404, which is certainly a bug.

### LINKED ISSUE #113: BUG - Conductor users appear as their IDs, not as their email addresses

### LINKED ISSUE #121: Contract update view changes
#### Definite changes
- [ ] Title of current step should be a question
- [x] Unify tabs
- [x] Actions accessible from all tabs: "Send email", "Extend contract", and "Add note"
- [ ] "Advertise" action from "Advertise" step creates a Beacon post
- [x] Add list of county agents for email drop down
- [x] Add list of department contacts for email drop down
- [x] Expose list of people following a contract
- [x] Cc field for emails
- [x] Send emails to multiple people
#### Larger issues / open questions
- [x] How to switch flows? At the "Received departmental review" step, the contract can be renewed, bid out, or left to expire. Each of these flows is different. How do we address the branching? Have 3 separate buttons that determine the rest of the steps shown?
- [x] A new spec number is assigned by the County if the contract goes out to bid. How to change the spec number when this happens? In the admin, or as an action on a specific step?

### LINKED ISSUE #207: Post opportunities to beacon directly from conductor
Offshoot of the mega-thread #121

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Extend a contract
- Switch flows for contracts
- Smarter search index, only rebuild when visible contracts change
- Smarter template filtering
- Better, less brittle tests
- Pull department into its own model
### Issues
- Fixes #113 
- Fixes #121 
- Fixes #106 (PR #220)
- Fixes #207 (PR #208)
### TODO
- [x] Allow switching back and forth (handle `IntegretyError` when trying to move back to a previous flow)
- [x] Flow switching tests
- [x] Handle completed contracts (#106)
### Screencaps

Update metadata, extend contracts

Switching flows

### CODE REVIEW

**Comment by bsmithgall** [comment]
@shellicious @hamhands 

Open question -- this pull request is kinda getting out of hand. Should I complete the remainder of open work on this branch, or spin out into smaller feature branches?

**Comment by msknee** [comment]
@bsmithgall smaller branches sounds right.

**Comment by hamhands** [comment]
+1 to what @shellicious said

**Comment by bsmithgall** [comment]
Ok, I'll do PRs directly into this (`conductor-detail-view`) branch. We can examine those individually and then do a conductor mega-merge. This will let us continue deploying beacon/other fixes.

**Pull request merged**
