### PR TITLE
Conductor refactor follows

### LINKED ISSUE #370: Refactor -- move all of the methods out of the contracts.py file onto the ContractBase class

### LINKED ISSUE #371: Conductor refactor -- break apart stage transitions
Should be two:
1. a `transition_to_next`. which goes to the next stage in the contract's flow.
2. a `jump_to_destination`, which goes to whatever the passed definition is

These should likely live on the `Flow` model as opposed to floating around as methods.

### LINKED ISSUE #377: Conductor should be able to kill contracts/let contracts die on the vine
Should be an available action.

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Major conductor, basic data model refactoring
- Removed a bunch of unused code
- Replaced a good number of integration tests with unit tests
### Issues
- Fixes #377 
- Fixes #371 
- Fixes #370

### CODE REVIEW

**Comment by msknee** [comment]
For #377, let's not use the phrase 'kill contract.'

Instead:
- remove contract from use
- disable and archive contract
- remove contract

**Comment by hamhands** [comment]
@shellicious while I agree with using a less violent word in spirit, we should probably stick with the language used by OMB as a rule.

**Comment by bsmithgall** [comment]
Can I merge this?

**Comment by bsmithgall** [comment]
Screenshots:

screen shot 2015-09-15 at 2 14 57 pm
screen shot 2015-09-15 at 2 13 02 pm

**Pull request merged**
