### PR TITLE
Timezone support

### LINKED ISSUE #363: Add configurable date/timezone localization

### LINKED ISSUE #369: Conductor staff can post directly to Beacon from Conductor
While OMB is in transition, I don't see great harm in allowing staff with the conductor role to post directly to Beacon about opportunities.

### LINKED ISSUE #422: ublock (ad blocker) blocks beacon.js
A pretty funny bug:

img

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Added new DISPLAY_TIMEZONE configuration flag
- Force all dates to be UTC time before saving in database
- Flip the datepicker for a datetimepicker
- Add time support for Beacon
### Issues
- Fixes #363
- Fixes #369 
- Fixes #422 
### Screenshots

screen shot 2015-09-22 at 10 39 01 pm
screen shot 2015-09-22 at 10 20 26 pm

### CODE REVIEW

**Comment by hamhands** [comment]
@bsmithgall could we remove the seconds from the date picker? It makes it pretty hard to read.

**Comment by hamhands** [comment]
Otherwise this is good to merge :+1:

**Comment by msknee** [comment]
Is there a reason why we don't display the time zone? Is it in EST?

**Comment by bsmithgall** [comment]
Yeah, we can display timezones on the Beacon page. On the the form page, I'd like to leave it because of the way that the `dateutil.parse` method works.

**Comment by bsmithgall** [comment]
screen shot 2015-09-23 at 2 27 03 pm

**Comment by bsmithgall** [comment]
screen shot 2015-09-23 at 2 28 03 pm

**Comment by msknee** [comment]
:+1:

**Comment by bsmithgall** [comment]
HEADS UP @shellicious @hamhands after this gets deployed, we might have to go back and adjust the times on the currently posted opportunities to make them right. Otherwise, they might display as being closed at 8pm the day before they are actually due (because everything is stored right now as just a date with no time zone)

**Comment by hamhands** [comment]
:+1:

**Pull request merged**
