### PR TITLE
Conductor download all

### LINKED ISSUE #577: Bulk download of all contracts in conductor
@rileystewart could you clarify what you mean by "all"

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Added an option to download all, along with documentation for the new view method
### Issues
- Fixes #577 
### Screenshots

screen shot 2015-11-11 at 1 06 52 pm
screen shot 2015-11-11 at 1 06 33 pm

### CODE REVIEW

**Comment by msknee** [comment]
:+1:

What are the columns in the tsv when you download all?

**Comment by bsmithgall** [comment]
It's in the docstring for the method:

```
    Returns:
        A tsv follow with the following fields: the contract's id
        (item_number) contract's parent id (parent_item_number),
        the contract's description (description), the contract's
        expiration date (expiration_date) the contract parent's
        expiration date (parent_expiration), the department name
        (department), the assigned user's email address (assigned_to),
        the contract's spec number (spec_number), the contract
        parent's spec number (parent_spec), and a string with
        the status of a contract
```

**Comment by hamhands** [comment]
LGTM

**Comment by msknee** [comment]
Great, LGTM

**Pull request merged**
