### PR TITLE
opportunities model

### LINKED ISSUE #16: Prototype of Opportunities Site
NOTE this is for the EXTERNALLY facing piece.

### LINKED ISSUE #33: Parent categories not fully deduped
screen shot 2015-05-27 at 5 46 00 pm

Can we also standardize `and` vs. `&`

> Medical Supplies | Medical Supplies & Services
> Office Supplies and furniture | Office supplies and services
>  Planning, architectural, and engineering services | Planning, architecture, and engineering services

### LINKED ISSUE #34: Opportunities site should send confirmation emails
@hamhands can we grab the html from the cleaning-pgh emails you sent out?

### PR DESCRIPTION
**Pull request by hamhands**
### What changed
- first stab at opportunities data model
### Issues
- Closes #33 
- Closes #34 
- Closes #16

### CODE REVIEW

**Comment by bsmithgall** [comment]
TODO:
- [x] Clean up the categories/subcategories on google drive
- [x] Manage task for importing all categories/subcategories into database
- [x] Signup form successfully creates uses
- [x] Integration with email
- [x] AJAX calls to update the categories/subcategories (is this overkill? should we just shove everything onto the page in a JSON blob?) (This is overkill, we are going to shove everything onto the page.)
- [x] Signup form successfully links vendors with categories
- [ ] Index has all of the proper content.
- [ ] Styles conform to the design mockups
- [x] Tests for opportunities site

@shellicious can you attach the design mockups here?

**Comment by msknee** [comment]
opportunities-06
opportunities-08
opportunities-09
opportunities-10

**Comment by msknee** [comment]
Style guidance:
- Yellow color is: #FFCE00
- Light gray is: #F2F2F2
- Bolded heading text is 36pt.
- Bolded heading text on the landing page ("The City of Pittsburgh...") is 48pt. The unbolded text below is 36pt.
- Text in the email sign-up box and button on the landing page, above the fold, is 24pt
- Body and button text is 18pt

If text appears too large, scale things down from 48 / 36 / 24 / 18 to 36 / 24 / 18 / 14.

**Comment by bsmithgall** [comment]
@shellicious how wide is this stuff? I'm working off of the default 12-column grid. I'm using only 10 columns across, which is 750px wide. Yours seem to be a bit wider; how does it look if you use that width?

**Comment by msknee** [comment]
@bsmithgall that should be fine. It's about 780px.

Pro-tip: Command+Shift+4 and clicking & dragging allows you to define an area of the screen to take a screenshot of. It ALSO allows you to measure stuff on-screen, for future width/height questions.

**Comment by bsmithgall** [comment]
30px changes spacing in the font-size pretty dramatically, though.

**Comment by bsmithgall** [comment]
Also, I'm going to have to write some JS to handle the "another category" piece.

**Comment by msknee** [comment]
750px instead of 780px should be fine, so you shouldn't have to blow up the font.

**Comment by msknee** [comment]
landingpage_splashimage_grayscalefire-11

**Comment by bsmithgall** [comment]
autom8

**Comment by msknee** [comment]
- [x] "Signup" should be "sign up" and over in the right. Vendors wouldn't see the admin/profile/login links, right? 
- [x] type in nav bar should be the same size
- [x] footer should be same width as body content
- [x] Try 1.5 spacing between lines on the text over the splash image, and the question text on the landing page. It looks slightly awkwardly close together.
- [x] 15px more spacing above and below 'add another category' button on Signup page.
- [x] same with 2nd Signup email field on landing page
- [x] signup form links don't go anywhere

**Comment by msknee** [comment]
- subcategories should be in regular caps (I can do this tomorrow)

**Comment by bsmithgall** [comment]
Everyone will see a login link, there's no sensible way to hide it (we couldn't tell if someone is a vendor unless they, for example, logged in and were tagged that way). The only solution would be to hide it from everyone, which I'm not sure is a great idea.

**Comment by bsmithgall** [comment]
> Type in navbar should be the same size

Are you talking about the brand thing on the left? That's just a placeholder until we get an actual logo. We can change it, but it will be more work to undo later, so I'm more in favor of just leaving it as is tbh.

**Comment by bsmithgall** [comment]
Can we center the footer? I know that you have a predisposition against centering, but in this case it really is a nice unification piece.

**Comment by bsmithgall** [comment]
Remaining TODO:
- [x] Add "All" choice for the dropdown selection
- [x] Dropdowns should be alphabetical
- [x] Links on the front page (either find them or make them not links)
- [x] Email templates sending properly
- [x] Mobile unsuck

**Pull request merged**
