### PR TITLE
Star, filter, and sort

### LINKED ISSUE #45: Wexplorer -- Star contracts (new feature)
Thanks @rileystewart!

### LINKED ISSUE #50: Filters & Sorting
- [x] Filtered searching by line items, company, contract description, etc
- [x] Column sort

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- New features: star a contract, filter by where you want matches, sort columns
### Issues
- Fixes #50 
- Fixes #45
### Screencap

autom8

### CODE REVIEW

**Comment by msknee** [comment]
nitpicky comment:
- [ ] add 20px of spacing between the word describing a check box, and the check box that comes after it.

Yay, starring!  Is the departmental list based on what people starred, or what they subscribed to?

**Comment by bsmithgall** [comment]
I added stars to the departmental list, because why not:

autom8

**Comment by hamhands** [comment]
@bsmithgall should we add a sort icon for this PR? [Some options to consider](https://thenounproject.com/search/?q=sort).

**Comment by bsmithgall** [comment]
Not convinced it's super necessary right now but could be it's own issue.

**Comment by hamhands** [comment]
Ok I'm on board with that. I'll open one.

**Pull request merged**
