### PR TITLE
Ready for production

### LINKED ISSUE #24: Get Ready for production (alpha)
Here are a list of tasks that need to be done before we can deploy:
- [x] Whitelist pittsburghpa.gov emails and autoassign them to staff roles, create a new post-login view that let's them set their department (and return/manage it in the future).
- [x] Add more robust logging
- [x] Handle static assets (either using Heroku bin scripts/full Dockerfile and an installed less precompiler, or migrating full on to S3 for static assets)
- [ ] Set up S3/dropbox/some other service to hold COSTARS contract documents
- [x] Add indices to the database
- [x] Added search for line items, contract properties. Potentially optimize these queries and/or add indices to the database to make things faster than mud.
- [ ] Visual style walkthrough with @shellicious 
- [x] Go through remaining [checklist for deployment-readiness](https://github.com/codeforamerica/howto/blob/master/launch_requirements.md)
- [x] Add to enginelight (switch with Wexplorer)
- [x] Update README with Sherpa information
- [x] Heroku doesn't support writing logs to files, so do something else instead of using a FileHandler (ask around on Slack, look at Heroku addons)
- [x] Try (harder!) to actually mock the Govbids thing.

### PR DESCRIPTION
**Pull request by bsmithgall**
Here are a list of tasks that need to be done before we can deploy:
- [x] Whitelist pittsburghpa.gov emails and autoassign them to staff roles, create a new post-login view that let's them set their department (and return/manage it in the future).
- [x] Add more robust logging
- [x] Handle static assets (either using Heroku bin scripts/full Dockerfile and an installed less precompiler, or migrating full on to S3 for static assets)
- [x] Set up S3/dropbox/some other service to hold COSTARS contract documents
- [x] Add indices to the database
- [x] Added search for line items, contract properties. Potentially optimize these queries and/or add indices to the database to make things faster than mud.
- [x] Visual style walkthrough with @shellicious 
- [x] Go through remaining [checklist for deployment-readiness](https://github.com/codeforamerica/howto/blob/master/launch_requirements.md)
- [x] Add to enginelight (switch with Wexplorer)
- [x] Update README with Sherpa information
- [x] Heroku doesn't support writing logs to files, so do something else instead of using a FileHandler (ask around on Slack, look at Heroku addons)
- [x] Try (harder!) to actually mock the Govbids thing.
### Issues
- Closes #24 
- Closes #25

### CODE REVIEW

**Comment by bsmithgall** [comment]
Still TODO for style fixes:
- [x] Update filter logic to not break from nav
- [x] Dropdowns for all the apps
- [x] Sherpa navbar
- [x] Jinja filter title case
- ~~Smarter scraping logic for percent discounts (ugh)~~ WONTFIX for this round
- [x] Figure out a way to go back to the search results
- [x] Move wexplorer side-search into wexplorer navbar
- [x] Promote link to contract into a top-level property on ContractBase, update importers
- [x] Make the well happen on the companies page
- [x] Filter page department name is actually a dropdown
- [x] Fix filter view

**Comment by bsmithgall** [comment]
New TODOs:
- [x] List o' Departments
- [x] Contract page text placement should align with well
- [x] Title case not in all places yet
- [x] URL still not working
- [x] Company name should probably be bolded

**Comment by msknee** [comment]
List of Departments from a 2015 Operating Budget -- I took the top categories only.  (http://apps.pittsburghpa.gov/mayorpeduto/2015_Operating_Budget_PDF.pdf)

City Council 
City Clerk’s Office 
Office of the Mayor 
Bureau of Neighborhood Empowerment 
Office of Management and Budget 
Innovation and Performance 
Commission on Human Relations 
City Controller 
Department of Finance 
Department of Law 
Ethics Board 
Office of Municipal Investigations 
Personnel and Civil Service Commission 
Department of City Planning 
Department of Permits, Licenses, and Inspections 
Department of Public Safety 
Department of Public Works
Department of Parks and Recreation 
Citizen Police Review Board

**Comment by hamhands** [comment]
Much strong
screen shot 2015-05-22 at 1 30 02 pm

**Pull request merged**
