### PR TITLE
Conductor cleanup

### LINKED ISSUE #276: There's no sensible way to "start new" on Conductor, which is problematic

### LINKED ISSUE #284: Reverting a contract has extra started/stopped in flow
Screenshot:

screen shot 2015-08-25 at 12 37 38 pm

### LINKED ISSUE #299: Decide on colors for Conductor activity stream

### LINKED ISSUE #308: Confusion about assigning contracts
### Highlights from OMB meeting:
- There is a need for contracts to be assigned to one person for life
- When someone calls with an issue about a contract, even after adoption, to know who worked on it before

I think we have a couple options here:
1.  Automatic assignment
   - Riley: assigning only happens with completely new contracts. Everyone has their own pool of contracts for as long as the contract is held or renewed or re-bid, etc.
   - Example: I have sports contracts because I worked with similar things last year
   - In this flow, the only time assignment would happen is for completely new contracts
2. Change the assignment language to something like "Work on this contract"

### LINKED ISSUE #309: Stage card additions
### From OMB meeting:

Ed: _what if there were a counter in each stage so we know how long it took?_
- I think the main thing here is that there should be some kind of count available in the stage card itself. What this actually looks like is an open question.
- Also need to add who took a certain action in cases where someone updates a contract not assigned to them
- How close contract is to expiring needs to be present somewhere in the update screen, whether on the stage card or elsewhere

### LINKED ISSUE #310: High-level note tracking
### From OMB meeting
- Some concern about having meta notes rather than stage-specific notes
- Might be a need to hand down information about a contract if renewed or re-bid
- Way to see all notes rather than having to click a stage
- Need for high-level notes about contract

### LINKED ISSUE #314: Additions to contract list
From OMB meeting:

At-a-glance information requested in contract list view (like a plus sign to expand each row):
- Using dept
- Contact info
- Controller #

### LINKED ISSUE #368: Add spec number to title div of detail page
Some contracts have similar names and spec numbers are the way to differentiate. Also, spec numbers starting with 'i' mean they're inquiry (less than 30k) bids, which signals to Ed or Stephanie that they should be bid out a slightly different way (skipping the EORC)

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Dramatic UI overhauls to conductor
  - Added new view for "create new"/"start work"
  - Major changes to the detail page, including icons, a single unified log for all notes/tasks, filters, and more
  - Changes to the timeline cards, add additional information about time taken
- Expandable rows for the "in progress table"
- Added some additional unit tests
- Other fixups, improvements
### Issues
- Fixes #276 
- Fixes #284 
- Fixes #299 
- Fixes #308 
- Fixes #309 
- Fixes #310 
- Fixes #314 
- Fixes #368 

For screenshots/screencaps, see the various issues.

### CODE REVIEW

**Comment by msknee** [comment]
#276 (add a new contract): :+1:

#284 (reverting contract fixes):
- [x] Make the reverted log (step with the refresh icon) blue too. Blue = things having to do with stages starting / stopping / getting revisited.

#299 (detail page colors and icons): :+1:

#308 (start work button / assign flow):
I like this flow for starting work! There should be a way to see who has been assigned to the contract-that-is-about-to-be-worked-on-and-born-anew so that Ed and Stephanie know which ones to assign themselves to. 

Options:
- Another column that lists the first name of the person that was assigned, with no actions attached to it. Re-assigning happens in the Start Work button flow. 
- \+ sign in the leftmost column that expands row to show name of person that was assigned

#309: :+1: 

#310: :+1:

#314:
- [ ] Remove outer border from table

#368:
- [ ] Option 1!

**Comment by bsmithgall** [comment]
screen shot 2015-09-11 at 1 06 42 pm

**Comment by bsmithgall** [comment]
screen shot 2015-09-11 at 1 08 43 pm

**Comment by msknee** [comment]
Changes look great @bsmithgall!

**Pull request merged**
