### PR TITLE
Scout filters

### LINKED ISSUE #269: Currently active filters should be preserved through new searches

### LINKED ISSUE #376: Filter Scout search by contract type
Now that there are so many COSTARS contracts, it would be good to be able to filter those out.

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
- Filters go from checkboxes to buttons, consistent with conductor
- Added filter for contract type
- Removed split filter/search form, unified into one form.
### Issues
- Fixes #376 
- Fixes #269 (WONTFIX)
### Screenshot

screen shot 2015-09-14 at 10 03 05 pm

### CODE REVIEW

**Comment by hamhands** [comment]
Does this still preserve the filters through future searches like the first commit did? I'm not seeing it here: 
filter

**Comment by hamhands** [comment]
Another question: do we want to keep the filter button or fire the filter whenever a button is clicked? My thinking is the latter option but I defer to @shellicious

**Comment by bsmithgall** [comment]
To answer your questions in order:
1. No it doesn't do that, and I think that is the correct behavior. In the new flow, the search term is preserved and attached to the form on the results page (see how it still says group?).
2. It's not really possible with the current way the search results work -- results come back from the database in paginated form, meaning there isn't a way to filter all of them. If you would want the filter to fire when clicked, you would get a bunch of page refreshes which would be quite annoying IMO.

**Comment by bsmithgall** [comment]
screen shot 2015-09-15 at 11 51 21 am

any thoughts on #269 behavior @shellicious ?

**Comment by msknee** [comment]
Looks good to me! One change -- change the default text in the drop down to "Type of contract"

**Pull request merged**
