### PR TITLE
hopefully final deduping, added consulting to all service categories

### LINKED ISSUE #97: Duplicate NIGP codes
@shellicious @hamhands looks like there are some exactly duplicates even inside the same parent categories. This needs to be fixed.

### PR DESCRIPTION
**Pull request by hamhands**
### What changed
- combined hospital and surgical equipment (46500 | 47500), changed from general services to medical services and public safety categories
- added consulting to all service categories

Closes #97

### CODE REVIEW

**Comment by bsmithgall** [comment]
Does it make sense for all of the consulting services to have the same examples?

**Comment by msknee** [comment]
@bsmithgall:

2 options:
- Remove "consulting services" from all broad categories, and keep the _examples_ associated with it in human-friendly categories that make more sense (ex: "urban planning consulting" is in "planning, development, and surveying services"). 
- Differentiate "consulting services" associated with each broad category by removing examples (ex: for "consulting services" under "Events and recreation...", remove examples that don't have to do with events and recreation).  This sounds like the more tedious option, so I recommend going with the first, as long as it doesn't f up the data.

@hamhands, thoughts?

**Comment by bsmithgall** [comment]
No opinion.

**Comment by bsmithgall** [comment]
@hamhands if you get a chance, can you address the comments from @shellicious above? I'd like to get this merged.

**Comment by hamhands** [comment]
@bsmithgall @shellicious at this point do the examples really matter? We're not displaying them anywhere yet right?

**Comment by bsmithgall** [comment]
What did we decide to end up doing with this? @shellicious ?

**Comment by msknee** [comment]
Let's just keep it as it is and forget about the duplicate examples for now.

**Pull request merged**
